### ISSUE TITLE
filename cases don't match

### ISSUE THREAD

**Issue by yuliangruan** [ColdBox/cbox-debugger#5]
includes/panels/profilePanel refers to /cbdebugger/includes/DebugHeader.cfm
actual file is debugHeader.cfm

models/DebuggerService.cfm refers to /cbdebugger/includes/panels/ProfilerPanel.cfm
actual file is profilerPanel.cfm

alot of other references too.   includes/Debug.cfm,  appenders/*

**Comment by lmajano** [comment]
fixed now
